[project]
name = "countdown"
version = "0.1.0"
description = "A countdown script that can be used as a timer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "rich>=14.0.0",
]
